# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: carlosless

# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: backend-shop

# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend-shop

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
  
  importFileParser:
    handler: importFileParser.handler
    events:
      - s3:
          bucket: some-b-2345
          event: s3:ObjectCreated:*
          existing: true